### ISSUE TITLE
Debug version was shipped on NuGet, crashing apps on Debug.Assert

### ISSUE THREAD

**Issue by dasMulli** [ststeiger/PdfSharpCore#11]
The version distributed on NuGet was built in Debug configuration and crashes apps on `Debug.Assert()` statements (in our case inside `PdfString`).
This is super bad because it will use `Environment.FailFast()` when run in production, crashing the app without an option to recover. Even more unhelpful: the asp.net core IIS module doesn't restart the app in this case and continues to send 502 responses until the app pool is recycled. (which isn't your problem, but this is how we were alerted to the problem)

**Comment by dasMulli** [comment]
@startnow65 @ststeiger who's the owner of the NuGet package to help out here?

**Comment by startnow65** [comment]
Hi @dasMulli, sorry for the issue you experienced.
I'll look into it and give feedback shortly.
Thanks

**Comment by startnow65** [comment]
Hi @dasMulli, apologies again for the issues experienced.
A "release" version (1.0.3.1) has been pushed. Please update to that and let me know how it goes.
Thanks

**Comment by dasMulli** [comment]
Thanks @startnow65!

Well there have to be multiple things to come together here and there are multiple fixes (one of course being sanitizing input - but a debug.assert that crashes the app is weird here.. would have expected an `ArgumentException` or similar).
