### ISSUE TITLE
Debug output written to console

### ISSUE THREAD

**Issue by kevbry** [ststeiger/PdfSharpCore#111]
When using PdfSharpCore in a console project, opening a file and accessing a form leads to unexpected text being written to the console. Specifically in my case, each installed font is being written by FontResolver.cs, and something I haven't been able to find is writing the file path of the opened document.
Edit - the file path of the opened document was my fault, but the font paths being written out is definitely happening within the library.

**Comment by alfeg** [comment]
It's seems to be fixed here https://github.com/ststeiger/PdfSharpCore/pull/115

**Comment by ststeiger** [comment]
True.
