### ISSUE TITLE
The specified file has no valid PDF file header

### ISSUE THREAD

**Issue by sanglanun** [ststeiger/PdfSharpCore#12]
Hi,

I'm using your PdfSharp. It really awesome because working with .Net Core.

But now I get an error like below:
`ArgumentException: The specified file has no valid PDF file header.
Parameter name: path`

It happen when using below code:
`XPdfForm form = XPdfForm.FromFile(filePath);`

I check in the code, I suspect it because of the files in the [PdfReader](https://github.com/ststeiger/PdfSharpCore/blob/master/PdfSharpCore/Pdf.IO/PdfReader.cs) at line **162** like below:
`string header = PdfEncoders.RawEncoding.GetString(bytes, 0, bytes.Length); `

Whenever I using this, it always return PDF version as 0. So when I try using original code `string header = Encoding.ASCII.GetString(bytes);`, it working like charm, it will return with PDF version.

So, how do fix this? Or do you have suggestion for this? Or you can replace it using this below code
`string header = Encoding.ASCII.GetString(bytes); `

**Comment by ststeiger** [comment]
I'm not sure if this is correct, [the original code does not use ASCII](https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Pdf.IO/PdfReader.cs). 
Probably the file has been saved with a wrong encoding. 

We can do this, but it's probably better positioned inside the catch than used as default.

**Comment by sanglanun** [comment]
You really make my day. Hope will get an update soon including in the NuGet. Thanks.

**Comment by sanglanun** [comment]
Thanks for reply. Not sure about it, but i saw in version 1.32, it using ASCII. Anyway, hope you help me to update this and inside NuGet. Really appreciate your help. :-)

**Comment by startnow65** [comment]
@ststeiger The NuGet package would be updated in about 2hrs as i'm currently away.

**Comment by ststeiger** [comment]
No stress. 
We have all the time in the world ;)

**Comment by startnow65** [comment]
Great, NuGet updated..

**Comment by sanglanun** [comment]
Hi Guys, sorry for a late reply. Away from home yesterday.
I already try now, it still give me a '0' as a file version.
Now, I not sure where is the problem.

Below is my code to test pdf file:
`string filePath =  @"D:\sample.pdf";`
`var pdfversion = PdfReader.TestPdfFile(filePath); // give 0`

Then I try using from this [NuGet](https://www.nuget.org/packages/PdfSharp/1.50.4845-RC2a) in other test web app, tried the same code like above but it gave me '14' as pdf version.

Maybe the problem in the line 72 or 118. 
`public static int TestPdfFile(string path)`

When comparing [your code](https://github.com/ststeiger/PdfSharpCore/blob/master/PdfSharpCore/Pdf.IO/PdfReader.cs) with the [original code,](https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Pdf.IO/PdfReader.cs) there is 1 line different in the TestPdfFile method. It was in line 74.
`#if !NETFX_CORE && !PORTABLE`

Anyway, really appreciate your work and time. 👍

**Comment by ststeiger** [comment]
Ah, looked at it. 
There is indeed another bug. 
For some reason, it defines away the entire routine if NETFX_CORE is defined... 
Quick-Fixed that. 
@startnow65: Can you Nuget this again ? 

@sanglanun: Check if this works now (from source - or from nuget after startnow uploaded the new package). 
If it doesn't work afterwards, can you upload the sample.pdf somewhere ?

**Comment by sanglanun** [comment]
Awesome. I will wait for the nuget. Still new in the Asp .Net, so not sure how to use from the source yet. Anyway, I already try a lot pdf even from adobe site, still got '0' result. Hopefully it will work this time. :)

**Comment by startnow65** [comment]
Hey friends, so sorry for the delay, had some issues.
The nugget is live now

I may have to automate this process sometime soon...

**Comment by sanglanun** [comment]
Awesome guys. It works now. Thanks for your time and effort. 💯
