### ISSUE TITLE
Default FontResolver does not find fonts on Linux distribution Debian Buster

### ISSUE THREAD

**Issue by michalsznajder** [ststeiger/PdfSharpCore#127]
Default `FontResolver` on Linux tries to locate fonts by using `/etc/conf/fonts.conf``. On Debian Buster with package `fonts-dejavu-core` it means that directory `/usr/share/fonts` is searched for directories with fonts. However on Buster fonts are one directory lower:

```
root@h2895660:/usr/share# tree -d fonts
fonts
└── truetype <---- we scan here
    ├── dejavu   <--- fonts are lower
    ├── freefont
    └── ttf-dejavu

4 directories
``` 
This is caused by not recursively enumerating directories in:
https://github.com/ststeiger/PdfSharpCore/blob/aa843d41d1446dd5346795e640299a859142d4f8/PdfSharpCore/Utils/FontResolver.cs#L70-L75

Would you accept PR to scan here recursively?

**Comment by jilleJr** [comment]
@eltonina beat you to it :) #132

**Comment by ststeiger** [comment]
Already merged. ;)
