### ISSUE TITLE
Migradoc is not avaible when pdfsharcore is downloaded by nuget

### ISSUE THREAD

**Issue by rockbass2560** [ststeiger/PdfSharpCore#134]
First, thanks for this library.

I downloaded pdfsharpcore by nuget gallery. When I tried to use Migradoc classes, they aren't available to use (not downloaded).

Steps:
1. I executed Install-Package PdfSharpCore -Version 1.2.11 on nuget console
2. I tried to use or import any migracode class, but they aren't available.

**Comment by JoshGlue** [comment]
These are seperate NuGet packages: https://www.nuget.org/packages/MigraDocCore.DocumentObjectModel/ and https://www.nuget.org/packages/MigraDocCore.Rendering/ respectively

**Comment by rockbass2560** [comment]
Thanks for your answer. Would it possible to add that info in readme?
