### ISSUE TITLE
how to save MigraDoc.DocumentObjectModel.Document to Pdf?

### ISSUE THREAD

**Issue by Alex2021cyberhuman** [ststeiger/PdfSharpCore#135]
I am trying to save a document using PdfRenderer but I am getting an exception
What am i doing wrong?
I am trying to run it with windows 10 and net core 3.1
Code:
```
private void ExportPdf(string path, Document document)
{
      var render = new PdfDocumentRenderer(true)
      {
           Document = document
      };

            
render.RenderDocument();
render.PdfDocument.Save(path);
}
```
Exception info
  | Name | Value | Type
  | $exception | {"No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method."} | System.NotSupportedException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | 0x80131515 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method." | string
  | SerializationRemoteStackTraceString | null | string
  | SerializationStackTraceString | "   at System.Text.Encoding.GetEncoding(Int32 codepage)\r\n   at PdfSharp.Pdf.Internal.PdfEncoders.get_WinAnsiEncoding()\r\n   at PdfSharp.Fonts.OpenType.OpenTypeDescriptor.Initialize()\r\n   at PdfSharp.Fonts.OpenType.OpenTypeDescriptor..ctor(String fontDescriptorKey, XFont font)\r\n   at PdfSharp.Fonts.FontDescriptorCache.GetOrCreateDescriptorFor(XFont font)\r\n   at PdfSharp.Drawing.XFont.CreateDescriptorAndInitializeFontMetrics()\r\n   at PdfSharp.Drawing.XFont.Initialize()\r\n   at PdfSharp.Drawing.XFont..ctor(String familyName, Double emSize, XFontStyle style, XPdfFontOptions pdfOptions)\r\n   at MigraDoc.Rendering.FontHandler.FontToXFont(Font font, PdfFontEncoding encoding)\r\n   at MigraDoc.Rendering.ParagraphRenderer.get_CurrentFont()\r\n   at MigraDoc.Rendering.ParagraphRenderer.CalcCurrentVerticalInfo()\r\n   at MigraDoc.Rendering.ParagraphRenderer.InitFormat(Area area, FormatInfo previousFormatInfo)\r\n   at MigraDoc.Rendering.ParagraphRenderer.Format(Area area, FormatInfo previousFormatInfo)\r\n   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)\r\n   at MigraDoc.Rendering.FormattedHeaderFooter.Format(XGraphics gfx)\r\n   at MigraDoc.Rendering.FormattedDocument.FormatHeader(HeaderFooterPosition hfp, HeaderFooter header)\r\n   at MigraDoc.Rendering.FormattedDocument.FormatHeadersFooters()\r\n   at MigraDoc.Rendering.FormattedDocument.MigraDoc.Rendering.IAreaProvider.GetNextArea()\r\n   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)\r\n   at MigraDoc.Rendering.FormattedDocument.Format(XGraphics gfx)\r\n   at MigraDoc.Rendering.DocumentRenderer.PrepareDocument()\r\n   at MigraDoc.Rendering.PdfDocumentRenderer.PrepareDocumentRenderer(Boolean prepareCompletely)\r\n   at MigraDoc.Rendering.PdfDocumentRenderer.PrepareRenderPages()\r\n   at MigraDoc.Rendering.PdfDocumentRenderer.RenderDocument()\r\n   at BloodLab.App.Services.OrderReportPdf.ExportPdf(String path, Document document) in C:\\Users\\XYZtn21\\source\\repos\\Laboratory\\BloodLab\\BloodLab.App\\Services\\OrderReportPdf.cs:line 34\r\n   at BloodLab.App.Services.OrderReportPdf.Export(String path) in C:\\Users\\XYZtn21\\source\\repos\\Laboratory\\BloodLab\\BloodLab.App\\Services\\OrderReportPdf.cs:line 25\r\n   at BloodLab.ReportingTest.Program.Main(String[] args) in C:\\Users\\XYZtn21\\source\\repos\\Laboratory\\BloodLab\\BloodLab.ReportingTest\\Program.cs:line 81" | string
  | ▶ SerializationWatsonBuckets | {byte[0x000015f0]} | object {byte[]}
  | Source | "System.Private.CoreLib" | string
  | StackTrace | "   at System.Text.Encoding.GetEncoding(Int32 codepage)\r\n   at PdfSharp.Pdf.Internal.PdfEncoders.get_WinAnsiEncoding()\r\n   at PdfSharp.Fonts.OpenType.OpenTypeDescriptor.Initialize()\r\n   at PdfSharp.Fonts.OpenType.OpenTypeDescriptor..ctor(String fontDescriptorKey, XFont font)\r\n   at PdfSharp.Fonts.FontDescriptorCache.GetOrCreateDescriptorFor(XFont font)\r\n   at PdfSharp.Drawing.XFont.CreateDescriptorAndInitializeFontMetrics()\r\n   at PdfSharp.Drawing.XFont.Initialize()\r\n   at PdfSharp.Drawing.XFont..ctor(String familyName, Double emSize, XFontStyle style, XPdfFontOptions pdfOptions)\r\n   at MigraDoc.Rendering.FontHandler.FontToXFont(Font font, PdfFontEncoding encoding)\r\n   at MigraDoc.Rendering.ParagraphRenderer.get_CurrentFont()\r\n   at MigraDoc.Rendering.ParagraphRenderer.CalcCurrentVerticalInfo()\r\n   at MigraDoc.Rendering.ParagraphRenderer.InitFormat(Area area, FormatInfo previousFormatInfo)\r\n   at MigraDoc.Rendering.ParagraphRenderer.Format(Area area, FormatInfo previousFormatInfo)\r\n   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)\r\n   at MigraDoc.Rendering.FormattedHeaderFooter.Format(XGraphics gfx)\r\n   at MigraDoc.Rendering.FormattedDocument.FormatHeader(HeaderFooterPosition hfp, HeaderFooter header)\r\n   at MigraDoc.Rendering.FormattedDocument.FormatHeadersFooters()\r\n   at MigraDoc.Rendering.FormattedDocument.MigraDoc.Rendering.IAreaProvider.GetNextArea()\r\n   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)\r\n   at MigraDoc.Rendering.FormattedDocument.Format(XGraphics gfx)\r\n   at MigraDoc.Rendering.DocumentRenderer.PrepareDocument()\r\n   at MigraDoc.Rendering.PdfDocumentRenderer.PrepareDocumentRenderer(Boolean prepareCompletely)\r\n   at MigraDoc.Rendering.PdfDocumentRenderer.PrepareRenderPages()\r\n   at MigraDoc.Rendering.PdfDocumentRenderer.RenderDocument()\r\n   at BloodLab.App.Services.OrderReportPdf.ExportPdf(String path, Document document) in C:\\Users\\XYZtn21\\source\\repos\\Laboratory\\BloodLab\\BloodLab.App\\Services\\OrderReportPdf.cs:line 34\r\n   at BloodLab.App.Services.OrderReportPdf.Export(String path) in C:\\Users\\XYZtn21\\source\\repos\\Laboratory\\BloodLab\\BloodLab.App\\Services\\OrderReportPdf.cs:line 25\r\n   at BloodLab.ReportingTest.Program.Main(String[] args) in C:\\Users\\XYZtn21\\source\\repos\\Laboratory\\BloodLab\\BloodLab.ReportingTest\\Program.cs:line 81" | string
  | ▶ TargetSite | {System.Text.Encoding GetEncoding(Int32)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

**Comment by gregbrant2** [comment]
@Alex2021cyberhuman  I call

```
 var renderer = new PdfDocumentRenderer(true)
  {
      Document = document
  };
  
  renderer.PrepareRenderPages();
  renderer.RenderDocument();
  
  renderer.Save("test.pdf");
```

**Comment by Prologh** [comment]
@Alex2021cyberhuman .NET Core requires additional encoding, see [this SO question](https://stackoverflow.com/questions/50858209/system-notsupportedexception-no-data-is-available-for-encoding-1252).
