### ISSUE TITLE
Generating a pdf from a jpg seems to change the image quality

### ISSUE THREAD

**Issue by JHBonarius** [ststeiger/PdfSharpCore#139]
I'm using the following code to convert a jpg to a pdf
```
public void Convert(string inputFilePath, string outpFilePath)
{
    using var document = new PdfDocument();
    var page = document.AddPage();
    using (var image = XImage.FromFile(inputFilePath))
    {
        page.Width = image.PixelWidth;
        page.Height = image.PixelHeight;
        using var gfx = XGraphics.FromPdfPage(page);
        gfx.DrawImage(image, 0, 0, image.PixelWidth, image.PixelHeight);
    }
    document.Save(outpFilePath);
}
```
But this seems to degrade the jpg image quality.
![PdfSharpJpgToPdfDegrade](https://user-images.githubusercontent.com/36847155/107847452-08a9fe80-6dec-11eb-9786-66d722241ee6.png)
Also the pdf size is ~400kB, while the jpg is ~1MB. What's happening here?

**Comment by ststeiger** [comment]
Lossy image compression, apparently - somewhere.

**Comment by JHBonarius** [comment]
Yeah, probably. I find it strange that the image is recompressed when importing to PDF. I thought you could just 1-on-1 embed a jpg in a pdf?

Anyhow, my new solution is to import it manually using an ImageSource
```
var imageSource = ImageSource.FromFile(inputFilePath, 95);
using (var image = XImage.FromImageSource(imageSource))
{
    image.Interpolate = false;
    page.Width = XUnit.FromPoint(image.PointWidth);
    page.Height = XUnit.FromPoint(image.PointHeight);
    using var gfx = XGraphics.FromPdfPage(page);
    gfx.DrawImage(image, 0, 0);
}
```
Note, for this to work, you need to set
```
if (ImageSource.ImageSourceImpl is null) ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();
// or: ImageSource.ImageSourceImpl ??= new ImageSharpImageSource<Rgba32>();
```
somewhere. (I do it in the constructor of my service)

Still, I think it would be better if `XImage.FromFile` would use the original quality setting (is that possible?).

**Comment by ststeiger** [comment]
@JHBonarius: Well, you can look at the source of XImage.FromFile, see what it does different, and send me a pull-request, if you want to.
