### ISSUE TITLE
Fork of PDF Sharp

### ISSUE THREAD

**Issue by jogibear9988** [ststeiger/PdfSharpCore#14]
I've also a Fork of PDF Sharp, wich I maintain https://github.com/dotnetprojects/PdfSharp/commits/master
where I've fixed some issues. 

Do you plan to support it? If so, I will look to bring my patches to your Base, because I would like if more people work on it.

My Fork also includes PdfSharp.Xps converter (from https://nathanpjones.com/2013/03/output-to-pdf-in-wpf-for-free/), but I could create a separate nuget for it

**Comment by ststeiger** [comment]
I'm happy to accept patches. 
Just send me a pull request and I'll merge it - if it contains nothing malicious that is. 
However, WPF does not work in .NET Core, nor can you compile against it. 
Microsoft won't support WPF before .NET Core 3.0, and even then only on Windows. 
To me, that defeats the idea of .NET Core, but if it will compile in 3.0 without breaking existing functionality on Linux, I'll happily add it.

**Comment by sekulicb** [comment]
Is Xps converter in this fork? It seems that this functionally is not ported?

**Comment by jogibear9988** [comment]
it‘s in my fork. I‘ve not yet found time to bring this to here...
