### ISSUE TITLE
[question] Project constants and target frameworks.

### ISSUE THREAD

**Issue by jafin** [ststeiger/PdfSharpCore#176]
Hi, interested in tidying some code, and just curious on status of symbols and target assemblies used in the code.

I see the default compile symbols are `RELEASE;NETCOREAPP1_1;PORTABLE`

Are all the below compile symbols valid for this project still or can they be discarded?

```
WPF
UWP
CORE
NETFX_CORE
GDI
SILVERLIGHT
```

Uncertain, since they are set in the project, suspect they are 'default'.  So conditional code marked up with these symbols can just become the default code line  and the `#IF` `#ELSE` conditional branch conditions removed?

```
PORTABLE
NETCOREAPP1_1 

```

Are these constants even required for a netstandard project?  (left overs from PCL project perhaps?)

```
__IOS__
__ANDROID__
```

#### Drop

- netstandard1.3; (or at least push it  to 1.6)

#### Support

- netstandard2.0
- net5.0

**Comment by parksquare** [comment]
In the [original file](https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/!internal/Directives.cs) it describes some of these. IMHO, the ones you listed can all be removed, the only one I'm not 100% sure about is 'CORE'.  

I deduced that NETFX_CORE and UWP are pretty much one and the same, the use of 'core' in the moniker is a bit misleading.

I have a branch where I've removed all obsolete compiler directives (except CORE), and have made PORTABLE or NETCOREAPP1_1 the default, unconditional code as you suggest. 

I also agree that .netstandard1.3 should be dropped, which would also remove the need for AgHacks.cs. 

'CORE' is described in the file linked above as 'independent of any particular .Net library', but some of the conditional code it brings in when set refers to GDI classes. I'm tempted to remove it.

Any thoughts?

**Comment by jafin** [comment]
@parksquare 👍🏻  from me regarding cleanup and simplifying the codebase.  
RE: `CORE` constant,  I'd use your best judgement what action to take (I haven't been in the codebase for a while)

**Comment by parksquare** [comment]
My branch is [here](https://github.com/parksquare/PdfSharpCore/tree/feature/tidy-compiler-directives), it's a bit epic so not sure how likely a PR back into the main project would go down.

**Comment by jafin** [comment]
#226 closes this.
