### ISSUE TITLE
Migradoc uses package reference

### ISSUE THREAD

**Issue by OregonGhost** [ststeiger/PdfSharpCore#178]
I have seen that project references have been changed to package references recently in #170. I'm not sure if that is the best solution for the problem discussed there, but moreover, it imposes a new problem for me:

I'm currently fixing the table performance issues for a project requiring lots of large tables, and I can't figure out how that is supposed to work if the code is not directly taken from the project in the same solution. For example, I make an interface change in MigradocCore.DocumentObjectModel, and then cannot compile MigradocCore.Rendering because the latter pulls the NuGet package, rather than taking the project from the same solution. In other words, I cannot compile the solution, which would be required to provide the NuGet package, which in turn is required for compiling the solution...

I could live with reverting the change locally and keep project references for me, but finally, when pushing the code, it won't build again, because it fetches an older version of MigradocCore.DocumentObjectModel, because *this build is actually just building the dependent package*!

How is this supposed to work? Is there something I don't see with working with changed packages which are all in one solution? Otherwise I would strongly suggest to revert that change and find a better solution for the problem from #170.

**Comment by ststeiger** [comment]
I completely agree with you. 
Problem is, when you add half nuget half project-references, then it generates odd errrors, because nuget is crap.

**Comment by OregonGhost** [comment]
Yeah, that's why I suggest to entirely revert back to project references. Because as it currently is, I cannot make any changes to Migradoc, which I need to do. I understand that there's some issue with references that was tried to be resolved with that change, but maybe really just generating the very same version into all three assemblies would remove the need for that?  I'd be fine with Version X of Migradoc referencing the very same version X of PdfSharp, and having that as exact or minimum requirement in each Nuget package :)

It seems that everything actually works fine with project references. The generated nuspec files reference the exact versions of the project references.

**Comment by startnow65** [comment]
Hmm.. when generating a nugget package for a project that has a project reference, it adds the dependency for the project but with a version equal to the version set for the nugget package being built.

If we revert to using all project references, then all the nugget packages in the solution would have to be published in sync, using the same version number so we can avoid the weird issues with dependency resolution.

Another option would be to make a change to PdfSharpCore, merge and get a new version of PdfSharpCore nugget. Then update the version of PdfSharpCore used in Migradoc to the version of PdfSharpCore nugget that includes the required change. This would obviously increase development cycle though.

I just felt being able to independently release the nuggets for the projects would be useful. But seems releasing them all at once is looking like a better solution.

I'm happy to update the pipeline to release all the nuggets at once with a single version number if we think that would benefit all parties.

**Comment by OregonGhost** [comment]
You're right that making a change to PdfSharpCore, update, then update Migradoc would work. But keep in mind that this also applies to MigradocCore.Rendering vs. MigradocCore.DocumentObjectModel (which, as I'm concerned, don't need to be separate), so it increases the development cycle even more, because it requires at least three separate steps. And then PdfSharpCore.Charting... Gets tedious fast. And for what I'm currently doing (updating MigradocCore.DocumentObjectModel for performance and testing), it still won't work locally (or I'm still missing a way to make it work better locally).

Since MigradocCore (Rendering + DocumentObjectModel) basically only makes sense in conjunction with PdfSharpCore (or does anybody actually use Migradoc without PdfSharp?), I think publishing them all at once would be ok :)

> Problem is, when you add half nuget half project-references, then it generates odd errrors, because nuget is crap.

Several of these problems can be avoided with Paket and carefully crafted packages, rather than the "magic" system that is in MSBuild/dotnet. I'm not suggesting to switch now, but I had a lot of "magic" problems in the past ;)

**Comment by OregonGhost** [comment]
OK, so how should I proceed? I have a branch I'd like to merge, but the branch cannot be built due to the package references. Should I revert the package reference change as a separate pull request? Or as part of my actual branch? Or would any of you revert the package reference change?

**Comment by ststeiger** [comment]
@startnow65, @OregonGhost: 
It seems to me that using a single version number would be the best way to move forward. 

Personally, I'd move to project references, which i had, but then I also don't want to break the build for everyone else who obvriously use nuget *may Cthulhu have mercy on their souls*.  It sufficed that a merged merge-request for the default-font-resolver did something like that. 

If either of you send me a pull request for any required changes for a single version number etc., I'd be happy to merge them.

**Comment by startnow65** [comment]
Ok, I'll send a PR shortly

**Comment by ststeiger** [comment]
Merged.
