### ISSUE TITLE
Image cannot be loaded. Available decoders: - BMP : BmpDecoder - PNG : PngDecoder - JPEG : JpegDecoder - GIF : GifDecoder 

### ISSUE THREAD

**Issue by primostasis123** [ststeiger/PdfSharpCore#199]
hello i know this is old but i get error using fromfile
converting tif to pdf

`PdfDocument s_document = new PdfDocument(); 
PdfPage page = s_document.AddPage(); 
XGraphics gfx = XGraphics.FromPdfPage(page); 
XImage image = XImage.FromFile(fileFullPath);`

anyone knows the problem?

**Comment by IldarKhayrutdinov** [comment]
@primostasis123 before there didn't support tiff format by `ImageSharp` (used by `PdfSharpCore`), now it should be to work, please check

**Comment by fogerau** [comment]
Hello, i still have this error with version 1.3.12

**Comment by brianpopow** [comment]
For TIFF support `ImageSharp` needs to be updated to 2.0.0

**Comment by fogerau** [comment]
Thank you very much. It works now
