### ISSUE TITLE
InvalidCastException upon Open

### ISSUE THREAD

**Issue by nezbo** [ststeiger/PdfSharpCore#2]
Hi there. I am trying to get the pdf parsing working in a .NET Core application, but receive this exception immediately upon trying to open the pdf:
```
exception	{System.InvalidCastException: Unable to cast object of type 'PdfSharpCore.Pdf.PdfInteger' to type 'System.IConvertible'.
   at System.Convert.ToInt32(Object value)
   at PdfSharpCore.Pdf.IO.Parser.GetStreamLength(PdfDictionary dict)
   at PdfSharpCore.Pdf.IO.Parser.ReadObject(PdfObject pdfObject, PdfObjectID objectID, Boolean includeReferences, Boolean fromObjecStream)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, PdfDocumentOpenMode openmode)
```
The code is simply this at the moment:
```
            Stream stream = File.OpenRead(path);
            PdfDocument book = PdfReader.Open(stream, PdfDocumentOpenMode.ReadOnly);
            Console.WriteLine(string.Format("\tPageCount = {0}", book.PageCount));
```
where it fails on the second one. Any suggestions on how to fix the issue?

I have tested with [this pdf](http://www.africau.edu/images/default/sample.pdf) (placed in local filesystem)

**Comment by ststeiger** [comment]
Do you get this error as well if you do that with non-CORE PdfSharp ? 
e.g. try with PdfSharp for .NET 4 or .NET 2.0
If yes, that's a PdfSharp bug. 
I got this error/similar-error before on normal versions of PdfSharp.

**Comment by gvamsilatha** [comment]
I tried with .net standard project using PdfSharp, i am able to open the pdf document. looks like  PdfSharpcore has  issue with opening the pdf , it gives the below error 'Unable to cast object of type 'PdfSharpCore.Pdf.PdfInteger' to type 'System.IConvertible'.'

**Comment by ststeiger** [comment]
The issue has already been fixed. 
Maybe clone the latest version.

**Comment by gvamsilatha** [comment]
thanks for your quick response. Actually I am referencing the latest version of PdfSharpCore version 1.0.1 of nuget package. 
now I tried to clone the project, but couldnot load the projects in the soluciton file , I think because of CoreDb.shproj is not available when I clone. none of the projects were loaded in the solution file. 
![image](https://user-images.githubusercontent.com/25209664/41246577-25a22c5c-6d71-11e8-92b4-ad5a87a0a6b1.png)

**Comment by startnow65** [comment]
Hi gvamsilatha,

I have updated the Nuget Package with the latest fixes. Add the [Nuget package](https://www.nuget.org/packages/PdfSharpCore/1.0.2) to your project and test.

**Comment by gvamsilatha** [comment]
awesome. thanks a lot. its not throwing error now. I can play around with it now.
