### ISSUE TITLE
How can I get a background image on the pdf page

### ISSUE THREAD

**Issue by IngoManthey** [ststeiger/PdfSharpCore#203]
Can someone help me here how I can insert an image png file as a background image?

Thanks in advance for any hint and tip

**Comment by startnow65** [comment]
Hi @IngoManthey 

This is a rough snippet of how I do this today

``` C#
try
{
    // Read in the background image
    var background = XImage.FromStream(() => {
        return File.OpenRead("background.jpg");
    });

    // Create the document object
    PdfDocument pdfDocument = new PdfDocument();

    // Add a page to the document
    var page = pdfDocument.AddPage();

    // Get a graphics hande for the page
    var gfx = XGraphics.FromPdfPage(page, XPageDirection.Downwards);

    // Draw the image with the provided coordinates on the page
    gfx.DrawImage(background, 0, 0, 266, 192);
    
    // Draw additional text or anything else
    gfx.DrawString("Sample text on background", new XFont("Arial", 15, XFontStyle.Regular, new XPdfFontOptions(PdfFontEncoding.WinAnsi)), XBrushes.Black, new XPoint(10, 10));

    // Save the pdf document
    pdfDocument.Save("output.pdf");
}
catch (Exception ex)
{
    throw new Exception("Could not Generate PDF", ex);
}
```

**Comment by IngoManthey** [comment]
@startnow65 
Thank you for your help. 
Unfortunately, no background image can be inserted into a created pdf document with the code. I changed your code as follows:
`CreateDocument();

PdfDocumentRenderer renderer = new(true)
{
    Document = Pdf
};

if (!string.IsNullOrWhiteSpace(Invoice.BackgroundImage))
{
    renderer.PrepareRenderPages();
    int pages = renderer.DocumentRenderer.FormattedDocument.PageCount;
    var background = XImage.FromStream(() => {
        return System.IO.File.OpenRead(Invoice.BackgroundImage);
    });
    for (int i = 1; i <= pages; ++i)
    {
        PageInfo pageInfo = renderer.DocumentRenderer.FormattedDocument.GetPageInfo(i);

        PdfPage page = renderer.PdfDocument.AddPage();
        var gfx = XGraphics.FromPdfPage(page, XPageDirection.Downwards);
        gfx.DrawImage(background, 0, 0, pageInfo.Width, pageInfo.Height);
        renderer.DocumentRenderer.RenderPage(gfx, i);
    }
}
else
    renderer.RenderDocument();
if (!string.IsNullOrEmpty(password))
    SetPassword(renderer, password);
renderer.PdfDocument.Save(filename);`
