### ISSUE TITLE
Unable to cast object of type 'PdfSharpCore.Pdf.PdfInteger' to type 'System.IFormattable'

### ISSUE THREAD

**Issue by dinoinyourhead** [ststeiger/PdfSharpCore#208]
Please fix this issue, the issue occurs in PowerShell 7.x (PowerShell Core). The issue was fixed in the passed in version 1.0.2 from @max-brightspark (https://github.com/ststeiger/PdfSharpCore/commit/63e101da26e7973a3a3ae6289ef2012c36c7ab95) but was unforntunately overridden by @Marv51 (https://github.com/ststeiger/PdfSharpCore/commit/9dea78a928bff7b459c00f02c97736de406d5ff5)

You can reproduce the issue with following code

`Add-Type -Path "C:\tmp\PdfSharpCore\1.3.12\lib\net5.0\PdfSharpCore.dll"

$mergedPdf = New-Object PdfSharpCore.Pdf.PdfDocument

 foreach ($pdf in (Get-ChildItem -Path "C:\tmp\test\*.pdf"))
{
    $inputPdf = [PdfSharpCore.Pdf.IO.PdfReader]::Open($pdf, [PdfSharpCore.Pdf.IO.PdfDocumentOpenMode]::Import)
    $pages = $inputPdf.Pages
    for ($j = 0; $j -lt $pages.Count; $j++)
    {
        $mergedPdf.AddPage($pages.Item($j))
    }
}

format-default: Unable to cast object of type 'PdfSharpCore.Pdf.PdfInteger' to type 'System.IFormattable'.

$mergedPdf.Save("C:\tmp\mergedpdf.pdf")
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`

I would be excited if you could fix the issue! :-)

**Comment by dinoinyourhead** [comment]
my guess was not quite correct, sorry.

I have provided a fix:
https://github.com/ststeiger/PdfSharpCore/pull/209

**Comment by ststeiger** [comment]
The PdfInteger class has made trouble before. 
Thanks for the fix.
