### ISSUE TITLE
[question] Reading multipage tiffs with XImage

### ISSUE THREAD

**Issue by mediangraph** [ststeiger/PdfSharpCore#214]
I would like to ask if there is a possibility to read multipage tiffs anyhow using XImage.
The Image has possibility to set active frame and you can create XImage from the chosen frame. However if I read the tiff file using XImage.FromFile I only get the first page from the multipage tiff I'm processing. Is there any workaround for that or is it just a limitation of the library?

**Comment by parksquare** [comment]
It ultimately calls `XImage(string path)` and then `ImageSource.FromFile(path)`:

```
        XImage(string path)
        {
            if (ImageSource.ImageSourceImpl == null) ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();
            _source = ImageSource.FromFile(path);
            Initialize();
        }
```

You could probably create your own implementation based on `ImageSharpImageSource<Rgba32>` that could choose the desired frame.

**Comment by ststeiger** [comment]
@mediangraph: I've acutally already worked with GIF-frames with ImageSharp. 

See here: 
https://stackoverflow.com/questions/64023538/is-it-possible-to-merge-a-image1-gift-and-image2-jpg-with-net-or-javascript/64024072#64024072

And the ImageSharp-Code is here: 
https://github.com/ststeiger/AnimatedGif

**Comment by mediangraph** [comment]
Thanks for the suggestions! I managed to save each of the frames to memory stream first then read with XImage.FromStream and it seems to do the job :)
