### ISSUE TITLE
Error when loading bookmarks (outlines)

### ISSUE THREAD

**Issue by mdesy** [ststeiger/PdfSharpCore#217]
Hi,

I have an existing PDF document that has 3 bookmarks. I have installed the NuGet package **MigraDocCore.Rendering 1.3.16** and I open the document like this:
`using var pdf = PdfReader.Open(stream, PdfDocumentOpenMode.Modify);`

Then I have an extension method to find a page by bookmark name:
`var bookmark = pdf.Outlines.FirstOrDefault(b => b.Title.Equals(bookmarkName, StringComparison.OrdinalIgnoreCase));`

The following error is thrown when accessing Outlines:

```
   GetReal: Object is not a number.
   at PdfSharpCore.Pdf.PdfArray.ArrayElements.GetReal(Int32 index)
   at PdfSharpCore.Pdf.PdfOutline.SplitDestinationPage(PdfArray destination)
   at PdfSharpCore.Pdf.PdfOutline.Initialize()
   at PdfSharpCore.Pdf.PdfOutline.InitializeChildren()
   at PdfSharpCore.Pdf.PdfOutline.Initialize()
   at PdfSharpCore.Pdf.PdfOutline..ctor(PdfDictionary dict)
```

That code works in the original version of PdfSharp but not PdfSharpCore. Any idea of what could be causing the issue?

Thanks!

**Comment by pj-r** [comment]
I had the same problem.
Should be fixed here: https://github.com/ststeiger/PdfSharpCore/pull/223

**Comment by pj-r** [comment]
@mdesy The change is merged to master. Can you validate it works now for you?

**Comment by mdesy** [comment]
I can confirm the fix works, that's awesome thank you!
