### ISSUE TITLE
Cannot draw an image (jpeg)

### ISSUE THREAD

**Issue by sanglanun** [ststeiger/PdfSharpCore#22]
Hi, Im trying to draw an image (jpg) to pdf using pdfsharpcore. Below is my code.

            PdfDocument document = new PdfDocument();
            PdfPage page = document.AddPage();
            XGraphics gfx = XGraphics.FromPdfPage(page);
            XImage image = XImage.FromFile("D:\\imageFile.jpg");

            // draw image to pdf
            gfx.DrawImage(image, 0, 0, 250, 140);

            // Save the document...
            string filename = "D:\\test.pdf";
            document.Save(filename);

But it not working, it gave me an error. Can anyone help me?
Here I attach the error.
![1](https://user-images.githubusercontent.com/6336820/48456779-3d890e80-e7fb-11e8-9302-3be092384d2d.PNG)

**Comment by startnow65** [comment]
Hi, @sanglanun you'll need to implement an Image Source.

You can use [this implementation](https://github.com/ststeiger/PdfSharpCore/blob/master/PdfSharpCore.ImageSharp/ImageSharpImageSource.cs).
After implementing the class, add the line below to make the library use it.
`ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();`

You can add it as the first line for now, but should be preferably somewhere where it would be set once.

**Comment by sanglanun** [comment]
thanks. It works.
