### ISSUE TITLE
pdf fails to open

### ISSUE THREAD

**Issue by KlaskSkovby** [ststeiger/PdfSharpCore#222]
i have a pdf which fails to open with pdfSharp.  the pdf file is 448 KB

i have located it to that the Symbol is an Integer instead of an Xref. 

![image](https://user-images.githubusercontent.com/33638395/165229386-d1b61f01-3f51-424d-8980-ab5430f42195.png)

then in the ReadXRefStream function it goes into the "Hack" 

![image](https://user-images.githubusercontent.com/33638395/165230022-193e19bf-f1ae-475b-8ce5-d060fc0916b4.png)

and in the DecodeCrossReferenceStream function it throws the exception Invalid perdictor in array
![image](https://user-images.githubusercontent.com/33638395/165230055-0720826f-662d-4b53-adc9-49dfab0db023.png)

How do i fix this?

![image](https://user-images.githubusercontent.com/33638395/165230099-115c4e95-71ed-4f94-b511-7e40e2c61038.png)

Can this be the issue?
https://www.verypdf.com/document/pdf-format-reference/pg_0093.htm
For a file that has never been updated, the cross-reference section contains only one subsection, whose object numbering begins at 0

**Comment by jafin** [comment]
@KlaskSkovby Are you able to provide a test PDF with exhibits the error?

**Comment by KlaskSkovby** [comment]
yeah this pdf

https://drive.google.com/file/d/1JRxU4Ph0ktjRUX_RUEzsWkFcP_9UryFW/view

**Comment by jafin** [comment]
Can repro your issue 😔, sadly I'm out of my depth to offer a fix.

**Comment by packdat** [comment]
The issue with the attached pdf was that it actually uses ALL 5 filter-types defined in the [PNG-spec](https://datatracker.ietf.org/doc/html/rfc2083#section-6) for encoding the CrossReferenceStream.
PdfSharp(Core) supports only filter type 2. (the value that is checked in method `DecodeCrossReferenceStream`)

I created #234 that adds support for the missing PNG-filters.
With these changes i was able to open the attached pdf without issues.

**Comment by KlaskSkovby** [comment]
> The issue with the attached pdf was that it actually uses ALL 5 filter-types defined in the [PNG-spec](https://datatracker.ietf.org/doc/html/rfc2083#section-6) for encoding the CrossReferenceStream. PdfSharp(Core) supports only filter type 2. (the value that is checked in method `DecodeCrossReferenceStream`)
> 
> I created #234 that adds support for the missing PNG-filters. With these changes i was able to open the attached pdf without issues.

I have tested this and it works, i can now open and merge it. thanks for the fix packdat. 
However it strips the pdf of the annotations - how can that be?
