### ISSUE TITLE
Outline.Add

### ISSUE THREAD

**Issue by KlaskSkovby** [ststeiger/PdfSharpCore#235]
i just converted from pdfsharp to pdfsharpCore

however now i can't add bookmarks to my pdf document. 
i don't get any exception, so can't follow the stack trace.

and when i do a pdfDocument.Outlines.Count() before saving and after all bookmarks have been added it counts zero.

Has anything changed with outline since the original pdfSharp i'm unaware of?

**Comment by KlaskSkovby** [comment]
Ok this is weird. 

The pdfSharpCore actually adds the bookmarks. 
I can see them in Adobe reader, but can't see them in Bluebeam Revu. 

This is only an issue after i ported to pdfSharpCore
Can it be a Font issue?

**Comment by jafin** [comment]
Hi @KlaskSkovby ,

I can't answer your what changed question, I had a quick look between the repos, and nothing stood out.

I ran this demo, it appears to open in Foxit/Acrobat with bookmarks.  Not sure if that gives any clues?


```c#
  [Fact]
        public void CanCreateDocumentWithOutlines()
        {
            var document = new PdfDocument();
            var font = new XFont("Verdana", 16);
            var page = document.AddPage();
            var gfx = XGraphics.FromPdfPage(page);
            gfx.DrawString("Page 1", font, XBrushes.Black, 20, 50, XStringFormats.Default);

            // Create the root bookmark. You can set the style and the color.
            var outline = document.Outlines.Add("Root", page, true,
                PdfOutlineStyle.Bold, XColors.Red);

            // Create some more pages
            for (var idx = 2; idx <= 5; idx++)
            {
                page = document.AddPage();
                gfx = XGraphics.FromPdfPage(page);

                var text = $"Page {idx}";
                gfx.DrawString(text, font, XBrushes.Black, 20, 50, XStringFormats.Default);

                // Create a sub bookmark
                outline.Outlines.Add(text, page, true);
            }

            document.Outlines.Count.Should().Be(1);

            //artifact
            var filename = "Bookmarks.pdf";
            document.Save(filename);
        }
```

![image](https://user-images.githubusercontent.com/127927/170993995-e6cd469d-599c-4ca8-957a-1a417321ff62.png)

**Comment by KlaskSkovby** [comment]
I changed to the Nuget package instead and it works.
