### ISSUE TITLE
Object already in table

### ISSUE THREAD

**Issue by cdenvir** [ststeiger/PdfSharpCore#28]
Could we please adjust the following so it logs a warning rather than throws an exception when there are duplicates in the PDF.  I have a PDF that will read in chrome, edge, adobe, and used to work in the .net framework iTextSharp version but it will not work with PdfSharpCore.  I understand it is technically an invalid PDF but the standard appears to be to ignore subsequent duplicates and keep the first encountered.

` throw new InvalidOperationException("Object already in table.");`

**Comment by ststeiger** [comment]
Fixed with 
https://github.com/ststeiger/PdfSharpCore/commit/e0092e1816159924eacba6014d016c23b81e24c4

Check if that works for you.
