### ISSUE TITLE
SharpZipBaseException on calling XGraphics.FromPdfPage

### ISSUE THREAD

**Issue by BennyM** [ststeiger/PdfSharpCore#29]
This issue https://github.com/empira/PDFsharp/issues/5 also exists in the code base.

**Comment by ststeiger** [comment]
Thanks for reporting. 
Fixed with commit https://github.com/ststeiger/PdfSharpCore/commit/79223c1a19b82b0cffc80029a876e52deb37085b

**Comment by ststeiger** [comment]
Thanks for reporting this.
