### ISSUE TITLE
End support for .NET 5

### ISSUE THREAD

**Issue by Marv51** [ststeiger/PdfSharpCore#294]
With the end of life/end of support for .NET 5 back in May 2022, I suggest dropping support for it.

I saw a couple other libraries drop support recently and with the upcoming .NET 7, this seems like a good time.

**Comment by kerams** [comment]
What would be the point of doing it?

On the other hand, the current TFMs look like this `netstandard2.0;netcoreapp3.1;net5.0;net6.0`. Unless there are specific optimizations in place for those Core TFMs all we'd really need is `netstandard2.0`.

**Comment by Marv51** [comment]
.NET 7 is imminent. So the TFM will be (hopefully?) `netstandard2.0;netcoreapp3.1;net5.0;net6.0;net7.0`
Which feels like a lot. 

Most people will no longer have .NET 5 installed on their machine, so any PRs will be untested on that version.

Are there really people out there updating to the newest PdfSharpCore but still use .NET 5 instead of Core 3.1 or .NET 6 (the LTS versions)?

**Comment by kerams** [comment]
> netstandard2.0;netcoreapp3.1;net5.0;net6.0;net7.0

Why would it be? Adding net7.0 serves no purpose.

**Comment by ststeiger** [comment]
I'll gladly add a build-reference for net7.0 when it comes out RTM. 
I'll not install any preview-version. 
Also, I don't see the point in removing net5.0 - it's too soon.  
As for usage - the pkg-build builds all these and creates all the binaries, so you don't need net5.0 installed if you just use the net7.0 nuget-package, once it is added. 
Also, if you build from source, you can just exclude net5.0 in the project file.

**Comment by Marv51** [comment]
Ok
