### ISSUE TITLE
use PdfSharpCore with Blazor Wasm

### ISSUE THREAD

**Issue by tossnet** [ststeiger/PdfSharpCore#299]
Has anyone found a solution to use this library with Blazor WebAssembly?
The problem is that FontResolver does not find the platform and returns the error "FontResolver not implemented for this platform (PdfSharpCore.Utils.FontResolver.cs)."

**Comment by mocox** [comment]
I use it in Blazor Wasm, actually i use it in a controller, call the controller and return the byte[] back then render it on front end as <object data="@_doc" width="800" height="800"></object>

var data = await Http.Post<byte[]>($"<your api>", html);
        _doc = "data:application/pdf;base64,";
        _doc += System.Convert.ToBase64String(data); ;

hopeit makes sense

**Comment by tossnet** [comment]
> I use it in Blazor Wasm, actually i use it in a controller, call the controller and return the byte[] back then render it on front end as
> 
> var data = await Http.Post<byte[]>($"", html); _doc = "data:application/pdf;base64,"; _doc += System.Convert.ToBase64String(data); ;
> 
> hopeit makes sense

But the problem with my issue is not exporting the PDF or offering it for download, it's that there is a problem with the "FontResolver"

**Comment by tossnet** [comment]
I found a solution to use the library on a Blazor Wasm app (Webassembly):  [https://github.com/tossnet/Blazor-PdfSharpCore/tree/master/Blazor.Wasm](url)
