### ISSUE TITLE
MigraDocCore.DocumentObjectModel.Document does not exist in the namespace MigraDocCore.DocumentObjectModel

### ISSUE THREAD

**Issue by jsutt88** [ststeiger/PdfSharpCore#3]
First, thanks for sharing this project!

I'm using your nuget package. I'm trying to use MigraDocCore's Document object for it's table features, but I'm getting an error "MigraDocCore.DocumentObjectModel.Document does not exist in the namespace MigraDocCore.DocumentObjectModel."

The Document class is implemented in this project here:
https://github.com/ststeiger/PdfSharpCore/blob/master/MigraDocCore.DocumentObjectModel/MigraDoc/MigraDoc.DocumentObjectModel/Document.cs

In fact the only MigraDocCore class I'm able to access is: MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource
Note the funky namespace path. Maybe that gives us a hint?

Cheers!

Edit: I believe the current nuget package does not contain the MigraDocCore.DocumentObjectModel DLL file. I was thrown off by MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource being accessible.

**Comment by ststeiger** [comment]
There is no NuGet package. 
I didn't make any NuGet package - it's source code only. 
If you downloaded something from NuGet, then it wasn't mine.
