### ISSUE TITLE
Symbol.Long not parsed - Unexpected token '4294180864' in PDF stream.

### ISSUE THREAD

**Issue by hippasus** [ststeiger/PdfSharpCore#303]
I'm getting PdfReaderException Unexpected token '4294180864' in PDF stream. The file may be corrupted. If you think this is a bug in PDFsharp, please send us your PDF file error while reading the file attached.
[6G57261103339.pdf](https://github.com/ststeiger/PdfSharpCore/files/9835439/6G57261103339.pdf)

It seems to be an issue in the ParseObject function where Symbol.Long is not handled.

**Comment by ststeiger** [comment]
Merged [Pull Reuqest 304](https://github.com/ststeiger/PdfSharpCore/pull/304)
Issue should be fixed.
