### ISSUE TITLE
MigraDocCore Pdf with unexpected font

### ISSUE THREAD

**Issue by wbison** [ststeiger/PdfSharpCore#313]
A Pdf rendered using `MigraDocCore.Rendering 1.3.43` in a .Net Core 7 application on Azure (Windows) is using an unexpected comicsans- like font.

Running the same code locally on a Mac results in a Pdf with a normal font but italic.

[This sample in the docs](https://github.com/ststeiger/PdfSharpCore/blob/master/docs/MigraDocCore/index.md
) includes a FontResolver line but I'm unsure what that does. 
``` c#
GlobalFontSettings.FontResolver = new FontResolver();
```
Adding the line as-is has no effect. Should I implement a customer resolver? How? 

[This sample](https://github.com/ststeiger/PdfSharpCore/blob/master/docs/MigraDocCore/index.md) includes a special PdfDocumentRenderer
``` c#
PdfDocumentRenderer pdfRenderer = new PdfDocumentRenderer(false,
PdfFontEmbedding.Always);
```
but the lib I use does not have a constructor with a second embedding option.

Any suggestions?

**Comment by wbison** [comment]
Was caused by specifying wrong font - duh :-(

**Comment by Thomas-HG** [comment]
Hi @wbison ,

I'm having the same issue as you on MacOS: I don't change any font parameters but the font in PDF is rendered in Italic...

How did you solve your issue ?

Thanks !

**Comment by wbison** [comment]
I had specified a non-existent font; this was not a problem in the original configuration but resulted in weird renderings on .Net 7/Windows.
