### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by calvinypark** [ststeiger/PdfSharpCore#34]
in **Pdf.IO\Lexer.cs**, line 568 (probably applies to 567 as well), if _nextChar == ' ' (empty space) for whatever reason, **Input string was not in a correct format** error is thrown.

**Comment by calvinypark** [comment]
I'm using pdf version 14 if that helps

**Comment by ststeiger** [comment]
I presume this is when reading a PDF. 
Can you upload a minimal PDF with which I can reproduce this error ?
