### ISSUE TITLE
DrawImage() on iOSDevice

### ISSUE THREAD

**Issue by Swiftee** [ststeiger/PdfSharpCore#35]
I'm trying to create a PDF in an iOS app using Xamarin, and it works fine on the simulator but running on a device gives this error:

> Attempting to JIT compile method 'SixLabors.ImageSharp.Formats.Png.PngDecoderCore:ProcessDefilteredScanline<SixLabors.ImageSharp.PixelFormats.Rgba32> (System.ReadOnlySpan`1<byte>,SixLabors.ImageSharp.ImageFrame`1<SixLabors.ImageSharp.PixelFormats.Rgba32>)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

This is triggered by calling the DrawImage() function, here's how I'm using it:
```
var page = document.AddPage();
page.Size = PageSize.A4;
var gfx = XGraphics.FromPdfPage(page);
XImage image = XImage.FromFile("icon.jpg");
gfx.DrawImage(image, new XRect(55, 767, 56, 37));
```

**Comment by ststeiger** [comment]
Sad, but most likely a bug in ImageSharp. 
I've updated the project to the latest ImageSharp. 
If the error persists, file a bug with ImageSharp, end reopen the issue once the ImageSharp-Team has released a new preview.
