### ISSUE TITLE
Infinite loop in inline image for malformed document

### ISSUE THREAD

**Issue by vpstuart** [ststeiger/PdfSharpCore#354]
I have an example of a document (which is sadly confidential) that goes when using ContentReader goes into an infinite loop in CLexer.ScanInlineImage.

I will post a PR shortly.

**Comment by stuartwmurray** [comment]
PR #355

**Comment by ststeiger** [comment]
Fixed with Commit [53b6876770c4f1cf610bb746bfcd82db53fb255f](https://github.com/ststeiger/PdfSharpCore/commit/53b6876770c4f1cf610bb746bfcd82db53fb255f).
