### ISSUE TITLE
PdfSharpCore w/ Azure

### ISSUE THREAD

**Issue by woofer4444** [ststeiger/PdfSharpCore#37]
Attempting to use this library with an asp.net core application hosted in Azure. The library is expecting Windows to be located on C:/ but for Azure App Services its located on the D:/. I believe the issue is in PdfSharpCore.Utils.FontResolver's static FontResolver and the fix would be to change @"C:\Windows\Fonts" to Environment.ExpandEnvironmentVariables(@"%SystemRoot%\Fonts") it would fix my issue

**Comment by ststeiger** [comment]
Fixed. Does that work for you ?

**Comment by woofer4444** [comment]
I'm using the nuget package not sure how to reference otherwise - would you be able to set it up as a prerelease for me to test?

**Comment by ststeiger** [comment]
@woofer4444: The nuget-package is owned by @startnow65.
I think his CI should create and publish a nuget automatically. 
If that is the case, you just have to update the package.

**Comment by woofer4444** [comment]
yea I saw the publishes going out after I typed that. Thanks I'll try it out and let you know

**Comment by woofer4444** [comment]
sorry for the late response, it's all working now - closing issue

**Comment by ststeiger** [comment]
Better late than never ;)
