### ISSUE TITLE
Image cannot be loaded. Available decoders: - BMP : BmpDecoder - PNG : PngDecoder - JPEG : JpegDecoder - GIF : GifDecoder

### ISSUE THREAD

**Issue by ValdirFerreira** [ststeiger/PdfSharpCore#39]
I was using PdfSharp, after upgrading to PdfSharpCore an error occurred to load the image in DrawImage.

It was PdfSharp this way and worked: XImage image = XImage.FromStream (Stream);
graphics.DrawImage (image, 5, 5, 586, 815);

After migrating to PdfSharpCore, the error started
Image can not be loaded. Available decoders: - BMP: BmpDecoder - PNG: PngDecoder - JPEG: JpegDecoder - GIF: GifDecoder

As I'm using now: XImage image = XImage.FromStream (() => Stream);
graphics.DrawImage (image, 5, 5, 586, 815);

the error happens here: graphics.DrawImage (image, 5, 5, 586, 815);
I've tried it anyway, does anyone know any formula to fix this?
Thank you.

**Comment by DevSide69** [comment]
I had this issue and solved it with 'Stream.position = 0',
I hope it will help you

**Comment by primostasis123** [comment]
hello i know this is old but i get same error using fromfile

`                                PdfDocument s_document = new PdfDocument();
                                PdfPage page = s_document.AddPage();
                                XGraphics gfx = XGraphics.FromPdfPage(page);
                                XImage image = XImage.FromFile(fileFullPath);`
                                
anyone knows the problem?

**Comment by a-k-t-e-r** [comment]
I've had the same Error occurrence, so I made that works for me like this way. For your kind information, during saving IFormFile into Stream I used below codes:
```
using (var fileStreamObj = new MemoryStream())
{
  file.CopyToAsync(fileStreamObj);
  fileStreamObj.Seek(0, SeekOrigin.Begin);
}
```
It's perfectly works for any files but images, so I need to convert into image format of SixLabors ImageSharp because PdfSharpCore uses SixLabors ImageSharp for image handling. Than, transform it into another MemoryStream along with the Set Position at the begining [it's importent, otherwise another exception will wait for you].
```
using (var image = Image.Load(fileStreamObj, out format))
{
  image.Save(imageStreamObj, format);
  imageStreamObj.Position = 0;
}
```
After that, PdfSharp Drawing will support this Stream further:
```
using (XImage img = XImage.FromStream(() => imageStreamObj))
{
     var height = (int)(pageWidthSize / (double)img.PixelWidth * img.PixelHeight);

    page.Width = pageWidthSize;
    page.Height = height;

    XGraphics gfx = XGraphics.FromPdfPage(page);
   gfx.DrawImage(img, 0, 0, pageWidthSize, height);
}
```

**Comment by Rahul-Vaity** [comment]
> ting to PdfSharpCore, the error started Image can not be loaded. Available decoders: - BMP: BmpDecoder - PNG: PngDecoder - JPEG: JpegDecoder - GIF: GifDecoder
> 
> As I'm using now: XImage image = XImage.FromStream (() => Stream); graphics.DrawImage (image, 5, 5, 586, 815);
> 
> the error happens here: graphics.DrawImage (image, 5, 5, 586, 815);

Unfortunately it's not working for me.

**Comment by Rahul-Vaity** [comment]
> array and then get the XImage from the memorystream will get a
> Image cannot be loaded error.

If I use version of ImageSharp 2.1.8 then it's working fine but same not working when I used latest version which is 3.1.4

**Comment by imranovfarid** [comment]
> I want to add setting Stream.position = 0 make no difference. It still crashes.

You need to do it after `imageBitmap.Save(msBit, ImageFormat.Png)` and before the `XImage image = XImage.FromStream(() => msBitmap);`

Finally, it works for me like this:

```
using Bitmap bitmap = QR.GetGraphic(10);
Image imageBit = bitmap;
imageBit.Save(msBit, ImageFormat.Png);
msBit.Position = 0;
XImage image = XImage.FromStream(() => msBit);
```
