### ISSUE TITLE
Missing Method Exception

### ISSUE THREAD

**Issue by TonyValenti** [ststeiger/PdfSharpCore#399]
Hi @ststeiger -
Can you please make this compatible with the latest version of ImageSharp?

I am currently getting this error:
```
System.MissingMethodException: 'Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(System.IO.Stream, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.'
```

I have the following packages installed in my project:
```
		<PackageReference Include="SixLabors.ImageSharp" Version="3.0.2" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.0.0" />
```

This is high priority for us.

Thank you for your help!

**Comment by TonyValenti** [comment]
@startnow65 - can you merge and release an update?

**Comment by TonyValenti** [comment]
Oh, do you know anyone who can?  This is urgent for use and I'm not sure how to contact @ststeiger .

**Comment by startnow65** [comment]
No, I don't know of anyone else

**Comment by igrek-cvna** [comment]
We have the exact problem with XImage.FromStream

**Comment by LewxX** [comment]
It looks like only @ststeiger has maintainer rights on this repo 😕,
and he only seams to come here once a month or so.

A possible workaround is to downgrade your ImageSharp version (if that's even possible in your environment):
`
 <PackageReference Include="SixLabors.ImageSharp" Version="2.*" />`

**Comment by ststeiger** [comment]
@[TonyValenti](https://github.com/TonyValenti): No I cannot, and for legal reasons. 
The new license of ImageSharp would create problems to existing users. 
Also, why remove old framework versions when everything works fine with them ?

**Comment by JimBobSquarePants** [comment]
>The new license of ImageSharp would create problems to existing users.

What legal problems are these? The license terms for ImageSharp are clear. As long as downstream consumers use the version bundled with PdfSharpCore as a transitive reference they are subject to the Apache 2.0 License.

https://github.com/SixLabors/ImageSharp/blob/f9268224253aa2cbfaee8d8acfdf8c33c8ad98c8/LICENSE#L33-L40

Your readme also references this?

https://github.com/ststeiger/PdfSharpCore/blob/cdf089b6c4d6b379aead95f463911dd009ae194e/README.md#L57-L60

**Comment by TonyValenti** [comment]
Hi @ststeiger -
JimBobSquarePants is the author and maintainer of ImageSharp and his post clearly indicates that there aren't any issues here.

Can you please merge the PR?
