### ISSUE TITLE
Can we take latest SixLabors / ImageSharp version which is v3.1.4

### ISSUE THREAD

**Issue by subahan-kothawal** [ststeiger/PdfSharpCore#436]
Can we take latest SixLabors / ImageSharp version which is v3.1.4. as the older one has vulnarabilities

**Comment by TonyValenti** [comment]
We are waning on @ststeiger to merge this PR:
https://github.com/ststeiger/PdfSharpCore/pull/427

**Comment by andylamb-rlg** [comment]
The later versions of SixLabors.ImageSharp have a different licence to the current dependent version.
The licence for version 1.0.4 is Apache 2.0. The licence for 3.1.4 is Apache 2.0 for non-commercial users, but for other uses a commercial licence is required. 
Does this complicate the licencing for packages that consume SixLabors.ImageSharp?

**Comment by JimBobSquarePants** [comment]
@andylamb-rlg your comment regarding the license is incorrect. For ImageSharp v3 and onward if users are only using the version installed transitively by this library they are subject to the terms of the Apache 2.0 license.
