### ISSUE TITLE
Unable to build UWP release version

### ISSUE THREAD

**Issue by ivanrlg** [ststeiger/PdfSharpCore#48]
Version Visual Studio 16.2.3
UWP target: 17763

I have done a project in Xamarin that includes its plugin, in Debug mode it works perfectly, but when I try to make the output in release mode I get the following error:

Error ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x86.microsoft.net.native.compiler\2.2.3\tools\x86\ilc\Tools\nutc_driver.exe @"C:\Users\Ivan Labradorr\source\repos\CinarucoProject\cinarucoproject\Cinaruco\Cinaruco.UWP\obj\x86\Release\ilc\intermediate\MDIL\Cinaruco.UWP.rsp"' returned exit code 1	Cinaruco.UWP		

Error: NUTC3033:Internal Compiler Error: Invalid MethodImpl body=6000353 decl=600032d when loading type 'SixLabors.ImageSharp.Processing.Processors.Quantization.PaletteQuantizer`1<TPixel>' from assembly 'SixLabors.ImageSharp' while loading MethodImpl list for 'instance SixLabors.ImageSharp.Processing.Processors.Quantization.IFrameQuantizer`1<TPixel1> SixLabors.ImageSharp.Processing.Processors.Quantization.PaletteQuantizer`1<TPixel>.SixLabors.ImageSharp.Processing.Processors.Quantization.IQuantizer.CreateFrameQuantizer<TPixel1>(SixLabors.ImageSharp.Configuration)'. while loading type 'SixLabors.ImageSharp.Processing.Processors.Quantization.PaletteQuantizer`1<TPixel>'. while computing compilation roots.	Cinaruco.UWP			
	
Type 'ZXing.Rendering.PixelData' from assembly 'ZXing' was not included in compilation, but was referenced in method 'bi.b(List<byte>, IBuffer, QrCodeModel, QrCodeLevel, int, int)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.	Cinaruco.UWP

**Comment by ststeiger** [comment]
This has nothing to do with PdfSharp.
