### ISSUE TITLE
Transparent Image is rendering with a black background

### ISSUE THREAD

**Issue by lavanyadeepak** [ststeiger/PdfSharpCore#49]
I am trying to embed a image with transparent background to a PDF using PDFSharp (for .NET Core). The image is rendering with a black background.

My guess is on Windows the transparent background is handled by GDIPlus.dll which might not be available on Linux. Do we have a workaround for it?

**Comment by ststeiger** [comment]
Do you have the latest nuget ? 
This was solved a month ago: 
https://github.com/ststeiger/PdfSharpCore/issues/41

**Comment by lavanyadeepak** [comment]
We are currently using 1.1.10. And it shows 1.1.12 as the latest latest one? Did you mean the latter?

![image](https://user-images.githubusercontent.com/2217926/64007252-6cc1ff80-cb31-11e9-99f6-4894e0d1047e.png)

**Comment by ststeiger** [comment]
1.1.12 should be it, yes
