### ISSUE TITLE
Problem with opening the document

### ISSUE THREAD

**Issue by AndrePScope** [ststeiger/PdfSharpCore#5]
Hi, I am trying to use PdfSharpCore in project .NetCoreApp,Version=v1.1.
"Microsoft.NETCore.App": {
      "version": "1.1.4",
      "type": "platform"
    },

But I have the problem with opening PDF.

This is the code:
**PdfDocument doc = PdfReader.Open(path);**
After openning the doc is null and I had no exception.

Please, describe what have do to open pdfdocument correct?

**Comment by elijadar** [comment]
The same issue. 
I looked into PdfReader.Open and it returns just null.
It looks like it is not possible to open a file in .net core.

**Comment by ancailliau** [comment]
Any update on that?

**Comment by gvamsilatha** [comment]
this issue still happening. when I open a file using PdfReader.Open, it returns just null in .net core. Is there any update on this please.

**Comment by startnow65** [comment]
Hi @gvamsilatha

I've created a pull request for it as the block turned off (FileStream operation) by the Compile switch works fine on .netCore.

I'll publish an updated nugget once @ststeiger takes a look and merges the PR.

**Comment by ststeiger** [comment]
It's merged. 
You can try now (from sourcecode on github).
