### ISSUE TITLE
NuGet packages for MigraDoc

### ISSUE THREAD

**Issue by HakanL** [ststeiger/PdfSharpCore#53]
It seems this fork of PdfSharp is very popular, it would be great if you could build a NuGet package for MigraDoc as well, so we'll have a complete set. Thanks!

**Comment by startnow65** [comment]
Hi @HakanL this would be looked into.
Thank you

**Comment by ststeiger** [comment]
Done.

**Comment by startnow65** [comment]
https://www.nuget.org/packages/MigraDocCore.DocumentObjectModel/
https://www.nuget.org/packages/MigraDocCore.Rendering/
