### ISSUE TITLE
Search by Arial is returning Arial Bold instead of Arial on Ubuntu

### ISSUE THREAD

**Issue by birado** [ststeiger/PdfSharpCore#56]
Font search's is considering the first occuring of related names to font name passed by parameter.
A cenario that i catched it is in a search by Arial on Ubuntu was returning Arial Bold instead of Arial.

To correct it i suggest to change method ResolveTypeface of class PdfSharpCore.Utils.FontResolver to it:

        public FontResolverInfo ResolveTypeface(string familyName, bool isBold, bool isItalic)
        {
            string ttfFile = fontfaceTofontfileMap.Keys.First(),
                tf, fontkey;

            familyName = familyName.ToLower();

            fontkey = familyName;
            if (isBold) fontkey += "b";
            if (isItalic) fontkey += "i";

            if (!fontfamilyTofontfaceMap.TryGetValue(fontkey, out ttfFile))
            {
                foreach (string fontfile in fontfaceTofontfileMap.Keys)
                {
                    tf = Path.GetFileNameWithoutExtension(fontfile).ToLower().TrimEnd('-', '_');

                    if (tf == familyName)
                    {
                        ttfFile = fontfile;

                        if (isBold && isItalic)
                        {
                            if ((tf.Contains("bold") && tf.Contains("italic")) || (tf.EndsWith("bi", StringComparison.Ordinal) || tf.EndsWith("ib", StringComparison.Ordinal)))
                            {
                                ttfFile = fontfile;
                                break;
                            }
                        }
                        else if (isBold)
                        {
                            if (tf.Contains("bold") || tf.EndsWith("b", StringComparison.Ordinal) || tf.EndsWith("bd", StringComparison.Ordinal))
                            {
                                ttfFile = fontfile;
                                break;
                            }
                        }
                        else if (isItalic)
                        {
                            if (tf.Contains("italic") || tf.EndsWith("i", StringComparison.Ordinal) || tf.EndsWith("ib", StringComparison.Ordinal))
                            {
                                ttfFile = fontfile;
                                break;
                            }
                        }
                        else
                        {
                            //We found a match on this font and did not want bold or italic.
                            //This is not guaranteed to always be correct, but the first matching key is usually the normal variant.
                            break;
                        }
                    }
                }
                if (string.IsNullOrWhiteSpace(ttfFile))
                {
                    foreach (string fontfile in fontfaceTofontfileMap.Keys)
                    {
                        tf = Path.GetFileNameWithoutExtension(fontfile).ToLower().TrimEnd('-', '_');

                        if (tf.Contains(familyName))
                        {
                            ttfFile = fontfile;

                            if (isBold && isItalic)
                            {
                                if ((tf.Contains("bold") && tf.Contains("italic")) || (tf.EndsWith("bi", StringComparison.Ordinal) || tf.EndsWith("ib", StringComparison.Ordinal)))
                                {
                                    ttfFile = fontfile;
                                    break;
                                }
                            }
                            else if (isBold)
                            {
                                if (tf.Contains("bold") || tf.EndsWith("b", StringComparison.Ordinal) || tf.EndsWith("bd", StringComparison.Ordinal))
                                {
                                    ttfFile = fontfile;
                                    break;
                                }
                            }
                            else if (isItalic)
                            {
                                if (tf.Contains("italic") || tf.EndsWith("i", StringComparison.Ordinal) || tf.EndsWith("ib", StringComparison.Ordinal))
                                {
                                    ttfFile = fontfile;
                                    break;
                                }
                            }
                            else
                            {
                                //We found a match on this font and did not want bold or italic.
                                //This is not guaranteed to always be correct, but the first matching key is usually the normal variant.
                                break;
                            }
                        }
                    }
                }

                fontfamilyTofontfaceMap.Add(fontkey, ttfFile);
            }

            if (ttfFile == null) ttfFile = fontfaceTofontfileMap.Keys.First();
            return new FontResolverInfo(ttfFile);
        }

**Comment by schtho** [comment]
I think #65 should also fix your issue.

**Comment by ststeiger** [comment]
@birado: Pull request 65 has been merged. 
Check if your problem is solved.

**Comment by mtarlac** [comment]
In my case, Arial Bold worked fine but instead of Arial (regular), it returns _Italic_.

The problem seems fixed now (Mint 18.3) and all Arial fonts works fine

Thanks
