### ISSUE TITLE
Issue with FontResolver on iOS

### ISSUE THREAD

**Issue by DevBNM** [ststeiger/PdfSharpCore#57]
Hello,

I try to use PdfSharpCore on iOS to fill AcroForm.
No problem on Window, but when I try on iPad this issues appear:

> System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) 
  at PdfSharpCore.Utils.FontResolver.ResolveTypeface (System.String familyName, System.Boolean isBold, System.Boolean isItalic) 
  at PdfSharpCore.Fonts.FontFactory.ResolveTypeface (System.String familyName, PdfSharpCore.Fonts.FontResolvingOptions fontResolvingOptions, System.String typefaceKey) 

Someone have an idea about that? Because I don't know how to fix it.

Best regards,
Alexis

**Comment by ststeiger** [comment]
Yea, that looks like it doesn't find the fonts folder on iOS, so it returns an empty font-list/enumerable. 
Could be fixed, if I knew how to list fonts on iOS, which I don't. 
And since I don't have iOS...

**Comment by DevBNM** [comment]
Hello,

I did some tests and I resolve the problem. 
I rewrite your FontResolver whith a different font directory path.

>       if (isOSX)
>         {
>             string fontDir = "/System/Library/Fonts/";
>             s_SupportedFonts = Directory.GetFiles(fontDir, "*.ttf", SearchOption.AllDirectories);
>             SetupFontsFiles();
>             return;
>         }

Now the problem is: System.Runtime.InteropServices.OSPlatform don't know the difference between MacOS and iOS. So you can't use InteropServices to check the OS, may be in the future thanks to .NET Core 5 ( https://github.com/dotnet/corefx/issues/27417 )

Thanks for your help and the library! :)

Best regards,
Alexis

**Comment by ststeiger** [comment]
Wel'll just check if the directory exists, then it should work.
