### ISSUE TITLE
System.IO.FileNotFoundException exception in linux ( Ubuntu 16.04)

### ISSUE THREAD

**Issue by aysegulgurmeric** [ststeiger/PdfSharpCore#63]
Hi,
I take the error as below in linux :
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PdfSharpCore, Version=1.1.18.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

But dll file is in the app folder. Do you have any idea?

Thank you.

**Comment by startnow65** [comment]
Hi @aysegulgurmeric please confirm that the user the app is running as has required permissions to the dll
