### ISSUE TITLE
AddPage does not clone Annotations

### ISSUE THREAD

**Issue by MrJonBirch** [ststeiger/PdfSharpCore#77]
This is a bug that was in PDFSharp. See this [link](https://forum.pdfsharp.net/viewtopic.php?f=3&t=3659).

Line 444 in PdfPages.cs needs to be uncommeted.
CloneElement(page, importPage, PdfPage.Keys.Annots, false);

**Comment by JuliusSenkus** [comment]
Having same issue [with this](https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Pdf/PdfPages.cs#L476).

**Comment by JuliusSenkus** [comment]
Would a PR with boolean flag (`DeepCopyAnotations`) that would enable deep copy of annotations be accepted (by default it would keep old behavior, users should explicitly enable it)?

**Comment by ststeiger** [comment]
Sure, why wouldn't it.

**Comment by JuliusSenkus** [comment]
Sorry for delay, was a bit busy with other projects.

**Comment by ststeiger** [comment]
merged it.

**Comment by JuliusSenkus** [comment]
Also what is your realese schedule (when I can wait for nuget)?

**Comment by JuliusSenkus** [comment]
@ststeiger ?

**Comment by ststeiger** [comment]
The nuget package should be generated automatically.

**Comment by startnow65** [comment]
Hi @JuliusSenkus the nugget is has been published.

It typically gets published after a pull request is merged
