### ISSUE TITLE
Change Imagesharp to Magick

### ISSUE THREAD

**Issue by ryanelian** [ststeiger/PdfSharpCore#79]
I saw this line in the project README and wanted to give my thoughts regarding the matter:

> ImageSharp being Alpha isn't a big issue either since this code isn't by far done yet. So please chime in ;)

The use of ImageSharp package for image manipulation is concerning due to upcoming AGPL license change: https://github.com/SixLabors/ImageSharp/issues/1024

On the other hand, Magick.NET and ImageMagick license are Apache 2 and they are well maintained.
- https://github.com/dlemstra/Magick.NET
- https://github.com/ImageMagick/ImageMagick/

**Comment by ststeiger** [comment]
Bastards. 
SkiaSharp would be the better alternative, IMHO.

**Comment by ryanelian** [comment]
I'd argue SkiaSharp is a mighty fine project, except that it weights almost 87MB (!!!)

**Comment by ststeiger** [comment]
But you don't ship that package in a release build.
Actually, the netstandard dll is 290.1 kB, and the runtime for Windows 10 is 7.2 MB (statically linked) 
 Where do you see 3MB for Linux native bindings ? 
They don't provide Linux native binding as far as I can see, which is quite odd, as they could just statically link everything.

**Comment by ryanelian** [comment]
https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux

**Comment by ryanelian** [comment]
I did a new issue on SkiaSharp for addressing the package size:

https://github.com/mono/SkiaSharp/issues/1241

Some support would be nice.

**Comment by ststeiger** [comment]
> https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux

But that's also around 7MB. 
Of course, if you put Windows, Linux, Mac, iOS, Android (ARM, x86, x64) into one file, you get a large file. But you ship platform executables, so that shouldn't be an issue.

**Comment by ctolkien** [comment]
FYI, ImageSharp have gone back to Apache2 license - https://github.com/SixLabors/ImageSharp/blob/master/LICENSE
