### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by baskren** [ststeiger/PdfSharpCore#86]
First, thank you for this excellent port of PdfSharpCore.   It is most helpful.

I have made some enhancements / changes required for a project on which I am working.  Specifically: 

  - Added XRadialGradientBrush, made a base class for XLinearGradientBrush and XRadialGradientBrush, and modified PdfGraphicsState.cs, PdfShading.cs, and PdfShadingPattern.cs to implement converting these changes into PDF code. 
  - Added XGraphicsPath.AddMove(double x, double y) because I couldn't figure out another way to support SVG, AndroidVector path data without doing so.

In this repo, XLinearGradientBrush still contains code specific to GDI, WPF, UWP, and Silverlight.  However, in the above enhancements / changes, I only made updates to the .NetStandard implementation.  My understanding is this project is supposed to be a .NetStandard fork of PdfSharp.  **If that is the case, would you be willing to accept a pull request from me with these extensions / changes?**

Thank you for your consideration.

**Comment by ststeiger** [comment]
Silverlight and UWP is dead, WPF semi-dead on life-support, and GDI is old garbage that should be removed. 

Send the pull request.

**Comment by baskren** [comment]
Cool.  Putting on the finishing touches.  Ended up having to also:

- Extend XPen to use an XBrush (instead of an XColor) in order to support gradient strokes.  
- Modify PdfEncoders.ToString(XColor color, PdfColorMode colorMode) to support gradients with transparent colors.

Is there a standard test suite this project is using?  I would like to be sure that last modification hasn't broken anything.

**Comment by ststeiger** [comment]
@baskren: There are no tests.

**Comment by baskren** [comment]
OK, pull request submitted.  Thanks for being willing to consider this.
