### ISSUE TITLE
Open function is returning null in asp.netCore

### ISSUE THREAD

**Issue by gvamsilatha** [ststeiger/PdfSharpCore#9]
https://github.com/ststeiger/PdfSharpCore/blob/ffe8f9587260550da4db60bd1e854938c4077a3f/PdfSharpCore/Pdf.IO/PdfReader.cs#L74

**Comment by startnow65** [comment]
Hi @gvamsilatha

I've created a pull request for it as the block turned off (FileStream operation) by the Compile switch works fine on .netCore.

I'll publish an updated nugget once @ststeiger takes a look and merges the PR.

**Comment by ststeiger** [comment]
Done.

**Comment by gvamsilatha** [comment]
Great. thanks.  Have you pushed the latest  nuget package?  I don't see any nuget updates. Could you please check and let me know.

**Comment by startnow65** [comment]
Hi @gvamsilatha the Nuget Package has been pushed.
Please test and let's know how it goes.

**Comment by gvamsilatha** [comment]
yes. now I see the latest version. thanks. I will check it out.
