### ISSUE TITLE
Converting pdf portrait pages to landscape

### ISSUE THREAD

**Issue by clement911** [ststeiger/PdfSharpCore#93]
How do I convert all pages in the pdf document from portrait to landscape orientation?

I tried the following code:

```
            var pdfDocPortait = PdfReader.Open(@"C:\Temp\Portait.pdf");

            foreach (var page in pdfDocPortait.Pages)
            {
                page.Orientation = PdfSharpCore.PageOrientation.Landscape;
                page.Rotate = 0; //I tried both with and without this line
            }
            pdfDocPortait.Save(@"C:\Temp\Landscape.pdf");
```

It did change the orientation of the page but unfortunately it also cut off some of the page content at the top.
Am I missing something?

**Comment by Bogdancev** [comment]
Hi clement911

I think it's incorrect place to ask questions such as yours. This project is merely an adoption of original one to work with .net core. These people did not develop it or know insides and outs of pdfs.
Though some might answer your question, but I suppose it would be better to ask it on original MigraDoc/PdfSharp forum.

Regards, Sergii

**Comment by ststeiger** [comment]
> It did change the orientation of the page but unfortunately it also cut off some of the page content at the top.
Am I missing something?

Well, if you rotate the page, you will have to rotate the content. 

But if I remember right, what you can do is tell the viewer to view this page rotated. 
Don't know if that applies to the whole pdf, though. 
Don't remember the code, though, you'll have to google that.

**Comment by ststeiger** [comment]
Does that work: 

http://forum.pdfsharp.com/viewtopic.php?f=2&t=1882
