### ISSUE TITLE
MigraDocCore Support Asian text adaptive line break?

### ISSUE THREAD

**Issue by myunQ** [ststeiger/PdfSharpCore#97]
Hello everyone.

I know that words separated by spaces can automatically wrap, while words that use non-space separated words (such as Chinese) do not automatically wrap.

How to set up to support Asian text wrapping? Or was it not initially supported?

```
const string str = "中国素有“室无瓷不雅观，人无瓷难尊”一说，瓷器（china）对于中国人（China）而言，有着深化骨血般的情感。18世纪初，波兰国王奥古斯都二世同样怀着对瓷器的挚爱，修建了欧洲第一个瓷窑，命名“麦森”。于是，这个为国王打造生活方式的品牌应运而生，阅历了300多年风雨进程的麦森现在已然成为德国甚至全欧洲的第一瓷器品牌，那些高雅的器物被人们赋予“白色黄金”之美誉。令人不可思议的是，这个阅历了11场战役、6个不同政党的品牌，现在仍然秉承着最初的理念，为人们打造精致、高雅的生活方式。";

// .....
section.AddParagraph(str);
```

**Comment by ststeiger** [comment]
Check the original if it was supported at all. 
What you could do is insert a whitespace after each non-latin character. 
I admit that would look odd, though. 
Perhaps there is some zero-width character, like the conditional soft-hyphen that you could use instead of white-space.

**Comment by ststeiger** [comment]
Here you go: 
https://en.wikipedia.org/wiki/Zero-width_space

> The zero-width space character is encoded in Unicode as U+200B ZERO WIDTH SPACE (HTML &#8203;).

**Comment by myunQ** [comment]
thank you very much for your help @Bogdancev @ststeiger .

I currently use
```
PdfSharpCore.Drawing.XGraphics.MeasureString(string text, XFont font)
```
 to solve the problem of adaptive line wrapping.

thank you very much for your help.

have a pleasant workday!
